apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandu-java-openshift-jenkins
  labels:
    app: pandu-java-openshift-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pandu-java-openshift-jenkins
  template:
    metadata:
      labels:
        app: pandu-java-openshift-jenkins
    spec:
      containers:
        - name: pandu-java-openshift-jenkins-container
          image: panduass/pandu-java-openshift-jenkins:__IMAGE_TAG__
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: pandu-java-openshift-jenkins
spec:
  selector:
    app: pandu-java-openshift-jenkins
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pandu-java-openshift-jenkins
spec:
  to:
    kind: Service
    name: pandu-java-openshift-jenkins
  port:
    targetPort: 8080
  tls:
    termination: edge
